# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'rspec', '~>3.6'

gem 'coderay', '~>1.1'

gem 'rack-test', '~>0.7'

gem 'sinatra', '~>2'


# Web server gems
gem 'thin', '~> 1.8'

gem 'puma', '~> 6.2'

gem 'http', '~> 5.1'
gem 'reel', '~> 0.6.1'
gem 'webrick', '~> 1.8'

# Database gems
gem 'sequel', '~> 5.68'
gem 'sqlite3', '~>1.4'
